# Generated by Django 5.1.4 on 2025-04-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code_article',
            field=models.CharField(max_length=50),
        ),
    ]
