# Generated by Django 5.2 on 2025-04-06 23:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('code_article', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('quantite_demandee', models.IntegerField(default=0)),
                ('stock_consomer', models.IntegerField(default=0)),
                ('stock_total', models.IntegerField(default=0)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_reception', models.ForeignKey(db_column='id_reception', on_delete=django.db.models.deletion.CASCADE, to='reception.reception')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
