# Generated by Django 5.1.4 on 2025-04-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande_achat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeachat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='commandedemande',
            options={'managed': True},
        ),
    ]
