# Generated by Django 5.1.4 on 2025-04-04 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('commande_achat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id_reception', models.AutoField(primary_key=True, serialize=False)),
                ('code_article', models.CharField(max_length=50)),
                ('quantite_unitaire', models.IntegerField(default=0)),
                ('designation', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('quantite_demandee', models.IntegerField()),
                ('quantite_receptionnee', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Non réceptionné', 'Non réceptionné'), ('Réceptionné', 'Réceptionné')], default='Non réceptionné', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('id_commande', models.ForeignKey(db_column='id_commande', on_delete=django.db.models.deletion.CASCADE, to='commande_achat.commandeachat')),
            ],
            options={
                'db_table': 'reception',
            },
        ),
    ]
