# Generated by Django 5.1.4 on 2025-04-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_reception_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='updated_at',
        ),
    ]
